### ISSUE TITLE
这句话描述不是很严谨，求证一下

### ISSUE THREAD

**Issue by weiruizhang** [zenany/zenany.github.io#2]
write once, run anywhere ：这是编程界长期以来的一个理念，跨平台的理想方案，Java、Web 是最成功的实践

这句描述中，Java和Web不是同个概念吧，一个是一门语言，一个是一种开发类别。或者你只是想表达JavaWeb？

**Comment by zenany** [comment]
其实两个技术栈的统称：
- Java ：它的核心理念就是让 Java 代码可以运行在任何平台，通过强大而虚拟机搞定了
- Web ：理念也是只要用 Web 技术开发的代码，在任何平台都可以运行，借助浏览器作为虚拟机搞定的
想表达的是 Java、Web 这两个技术栈做到了 write once, run anywhere 😄

抱歉，恢复晚了些

**Comment by weiruizhang** [comment]
好的，谢谢回复，我有点强迫症了。。哈哈
